#!/bin/sh

if test '!' -r kanjivg.eids
then
  exit 77
fi

./idsgrep \
  '|一|七|三|上|下|中|九|二|五|人|休|先|入|八|六|円|出|力|十|千|口|右|名|四|土|夕|大|天|女|子|字|学|小|山|川|左|年|手|文|日|早|月|木|本|村|林|校|森|正|気|水|火|犬|玉|王|生|田|男|町|白|百|目|石|空|立|竹|糸|耳|花|草|虫|見|貝|赤|足|車|金|雨|青音' \
  kanjivg.eids | wc -l > kvg1-out.$$
if echo 80 | diff kvg1-out.$$ -
then
  rm -f kvg1-out.$$
  exit 0
else
  rm -f kvg1-out.$$
  exit 1
fi
