# Makefile.in generated by automake 1.11.1 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009  Free Software Foundation,
# Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.



#
# Makefile source for IDSgrep
# Copyright (C) 2012, 2013  Matthew Skala
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
# Matthew Skala
# http://ansuz.sooke.bc.ca/
# mskala@ansuz.sooke.bc.ca
#

############################################################################

# BASIC AUTOTOOLS STUFF




pkgdatadir = $(datadir)/idsgrep
pkgincludedir = $(includedir)/idsgrep
pkglibdir = $(libdir)/idsgrep
pkglibexecdir = $(libexecdir)/idsgrep
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
#noinst_PROGRAMS = mkwcw$(EXEEXT)
bin_PROGRAMS = idsgrep$(EXEEXT)
subdir = .
DIST_COMMON = $(am__configure_deps) $(am__dist_pdf_DATA_DIST) \
	$(dist_noinst_SCRIPTS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(srcdir)/config.tex.in $(srcdir)/gnugetopt.h \
	$(srcdir)/idsgrep.1.in $(top_srcdir)/configure COPYING INSTALL \
	depcomp getopt.c getopt1.c install-sh missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_add_am_macro.m4 \
	$(top_srcdir)/m4/ax_am_jobserver.m4 \
	$(top_srcdir)/m4/ax_am_macros.m4 \
	$(top_srcdir)/m4/ax_append_to_file.m4 \
	$(top_srcdir)/m4/ax_c___attribute__.m4 \
	$(top_srcdir)/m4/ax_check_gnu_make.m4 \
	$(top_srcdir)/m4/ax_count_cpus.m4 \
	$(top_srcdir)/m4/ax_create_stdint_h.m4 \
	$(top_srcdir)/m4/ax_file_escapes.m4 \
	$(top_srcdir)/m4/ax_func_getopt_long.m4 \
	$(top_srcdir)/m4/ax_perl_module_version.m4 \
	$(top_srcdir)/m4/ax_print_to_file.m4 \
	$(top_srcdir)/m4/tsu_c_anon_union_struct.m4 \
	$(top_srcdir)/m4/tsu_c_gcc_builtin_bswap.m4 \
	$(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = idsgrep.1 config.tex getopt.h
CONFIG_CLEAN_VPATH_FILES =
am__installdirs = "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" \
	"$(DESTDIR)$(dictdir)" "$(DESTDIR)$(pdfdir)"
PROGRAMS = $(bin_PROGRAMS) $(noinst_PROGRAMS)
am_idsgrep_OBJECTS = assoc.$(OBJEXT) bitvec.$(OBJEXT) cook.$(OBJEXT) \
	hash.$(OBJEXT) idsgrep.$(OBJEXT) match.$(OBJEXT) \
	parse.$(OBJEXT) regex.$(OBJEXT) unilist.$(OBJEXT) \
	userpred.$(OBJEXT) widthtab.$(OBJEXT)
idsgrep_OBJECTS = $(am_idsgrep_OBJECTS)
idsgrep_LDADD = $(LDADD)
am__DEPENDENCIES_1 =
idsgrep_DEPENDENCIES =  $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
am_mkwcw_OBJECTS = mkwcw.$(OBJEXT)
mkwcw_OBJECTS = $(am_mkwcw_OBJECTS)
mkwcw_LDADD = $(LDADD)
mkwcw_DEPENDENCIES =  $(am__DEPENDENCIES_1) \
	$(am__DEPENDENCIES_1)
SCRIPTS = $(dist_noinst_SCRIPTS)
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(CCLD) $(AM_CFLAGS) $(CFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(idsgrep_SOURCES) $(mkwcw_SOURCES)
DIST_SOURCES = $(idsgrep_SOURCES) $(mkwcw_SOURCES)
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
man1dir = $(mandir)/man1
NROFF = nroff
MANS = $(man1_MANS)
am__dist_pdf_DATA_DIST = idsgrep.pdf
DATA = $(dict_DATA) $(dist_pdf_DATA)
ETAGS = etags
CTAGS = ctags
# If stdout is a non-dumb tty, use colors.  If test -t is not supported,
# then this fails; a conservative approach.  Of course do not redirect
# stdout here, just stderr.
am__tty_colors = \
red=; grn=; lgn=; blu=; std=; \
test "X$(AM_COLOR_TESTS)" != Xno \
&& test "X$$TERM" != Xdumb \
&& { test "X$(AM_COLOR_TESTS)" = Xalways || test -t 1 2>/dev/null; } \
&& { \
  red='[0;31m'; \
  grn='[0;32m'; \
  lgn='[1;32m'; \
  blu='[1;34m'; \
  std='[m'; \
}
# Restructured Text title and section.
am__rst_title = sed 's/.*/   &   /;h;s/./=/g;p;x;p;g;p;s/.*//'
am__rst_section = sed 'p;s/./=/g;p;g'
# Put stdin (possibly several lines separated by ".  ") in a box.
am__text_box = $(AWK) '{				\
  n = split($$0, lines, "\\.  "); max = 0;		\
  for (i = 1; i <= n; ++i)				\
    if (max < length(lines[i]))				\
      max = length(lines[i]);				\
  for (i = 0; i < max; ++i) line = line "=";		\
  print line;						\
  for (i = 1; i <= n; ++i) if (lines[i]) print lines[i];\
  print line;						\
}'
# Solaris 10 'make', and several other traditional 'make' implementations,
# pass "-e" to $(SHELL).  This contradicts POSIX.  Work around the problem
# by disabling -e (using the XSI extension "set +e") if it's set.
am__sh_e_setup = case $$- in *e*) set +e;; esac
# To be inserted before the command running the test.  Creates the
# directory for the log if needed.  Stores in $dir the directory
# containing $f, in $tst the test, in $log the log, and passes
# TESTS_ENVIRONMENT.  Save and restore TERM around use of
# TESTS_ENVIRONMENT, in case that unsets it.
am__check_pre = \
$(am__sh_e_setup);					\
$(am__vpath_adj_setup) $(am__vpath_adj)			\
srcdir=$(srcdir); export srcdir;			\
rm -f $@-t;						\
trap 'st=$$?; rm -f '\''$(abs_builddir)/$@-t'\''; (exit $$st); exit $$st' \
  1 2 13 15;						\
am__odir=`echo "./$@" | sed 's|/[^/]*$$||'`;		\
test "x$$am__odir" = x. || $(MKDIR_P) "$$am__odir" || exit $$?;	\
if test -f "./$$f"; then dir=./;			\
elif test -f "$$f"; then dir=;				\
else dir="$(srcdir)/"; fi;				\
tst=$$dir$$f; log='$@'; __SAVED_TERM=$$TERM;		\
$(TESTS_ENVIRONMENT)
RECHECK_LOGS = $(TEST_LOGS)
AM_RECURSIVE_TARGETS = check check-html recheck recheck-html
TEST_SUITE_LOG = test-suite.log
TEST_SUITE_HTML = $(TEST_SUITE_LOG:.log=.html)
TEST_EXTENSIONS =  .test
LOG_COMPILE = $(LOG_COMPILER) $(AM_LOG_FLAGS) $(LOG_FLAGS)
am__test_logs1 = $(TESTS:=.log)
am__test_logs2 = $(am__test_logs1:.log=.log)
TEST_LOGS = $(am__test_logs2:.test.log=.log)
TEST_LOG_COMPILE = $(TEST_LOG_COMPILER) $(AM_TEST_LOG_FLAGS) \
	$(TEST_LOG_FLAGS)
TEST_LOGS_TMP = $(TEST_LOGS:.log=.log-t)
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  { test ! -d "$(distdir)" \
    || { find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
         && rm -fr "$(distdir)"; }; }
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /home/jhuapl/Downloads/idsgrep-0.5.1-clean/missing --run aclocal-1.11
AMINCLUDE = aminclude.am
AMTAR = ${SHELL} /home/jhuapl/Downloads/idsgrep-0.5.1-clean/missing --run tar
AM_DEFAULT_VERBOSITY = 1
AUTOCONF = 
AUTOHEADER = ${SHELL} /home/jhuapl/Downloads/idsgrep-0.5.1-clean/missing --run autoheader
AUTOMAKE = 
AWK = mawk
CC = /home/jhuapl/Downloads/emsdk_portable/emscripten/master/emcc
CCDEPMODE = depmode=gcc3
CFLAGS = -O0 --llvm-opts 0
CHECKSUM = /usr/bin/sha256sum
CPP = /home/jhuapl/Downloads/emsdk_portable/emscripten/master/emcc -E
CPPFLAGS = 
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
EXPECT = 
GREP = /bin/grep
GZIP = /bin/gzip
ICONV = /usr/bin/iconv
INC_AMINCLUDE = include $(top_builddir)/aminclude.am
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
KLEKNEV = /bin/sh
LDFLAGS = 
LIBOBJS = 
LIBS = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /home/jhuapl/Downloads/idsgrep-0.5.1-clean/missing --run makeinfo
MKDIR_P = /bin/mkdir -p
OBJEXT = o
PACKAGE = idsgrep
PACKAGE_BUGREPORT = mskala@ansuz.sooke.bc.ca
PACKAGE_NAME = IDSgrep
PACKAGE_STRING = IDSgrep 0.5.1
PACKAGE_TARNAME = idsgrep
PACKAGE_URL = http://tsukurimashou.sourceforge.jp/idsgrep.php
PACKAGE_VERSION = 0.5.1
PATH_SEPARATOR = :
PCRE_CFLAGS = 
PCRE_LIBS = 
PERL = /usr/bin/perl
PKG_CONFIG = /usr/bin/pkg-config
SET_MAKE = 
SHELL = $(if $(wildcard /bin/sh),/bin/sh,/bin/sh)
STRIP = 
VERSION = 0.5.1
XELATEX = 
abs_builddir = /home/jhuapl/Downloads/idsgrep-0.5.1-clean
abs_srcdir = /home/jhuapl/Downloads/idsgrep-0.5.1-clean
abs_top_builddir = /home/jhuapl/Downloads/idsgrep-0.5.1-clean
abs_top_srcdir = /home/jhuapl/Downloads/idsgrep-0.5.1-clean
ac_ct_CC = /home/jhuapl/Downloads/emsdk_portable/emscripten/master/emcc
am__include = include
am__leading_dot = .
am__quote = 
am__tar = ${AMTAR} chof - "$$tardir"
am__untar = ${AMTAR} xf -
andt = 
bindir = ${exec_prefix}/bin
build_alias = 
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
dictdir = ${datarootdir}/dict
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
edict_decomp = cjkvi-j.eids
enable_cjkvi_style = j
enable_docs = no
exec_prefix = ${prefix}
flat_dictdir = /usr/local/share/dict
flat_docdir = /usr/local/share/doc/idsgrep
host_alias = 
htmldir = ${docdir}
ifGNUmake = 
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /home/jhuapl/Downloads/idsgrep-0.5.1-clean/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
release_date = March 27, 2014
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
with_chise_ids = no
with_edict2 = ./edict2.gz
with_kanjivg = ./kanjivg-20140816.xml.gz
with_tsuku_build = no
ACLOCAL_AMFLAGS = -I m4
mvp := $(if $(VPATH),$(VPATH),.)
empty := 
space := $(empty) $(empty)
comma := ,
percent = %

############################################################################

# SILENT BUILD BLINKENLIGHTS
TSU_V_REDIR = $(if $(AM_V_at),>& /dev/null)
ECHO_ANSI = echo
#ECHO_ANSI = echo -e
ansi_default = 
#ansi_default = \e[0m
ansi_red = 
#ansi_red = \e[31m
ansi_green = 
#ansi_green = \e[32m
ansi_yellow = 
#ansi_yellow = \e[33m
ansi_blue = 
#ansi_blue = \e[34m
ansi_magenta = 
#ansi_magenta = \e[35m
ansi_cyan = 
#ansi_cyan = \e[36m
ansi_pink = 
#ansi_pink = \e[35;1m
ansi_white = 
#ansi_white = \e[37;1m
ansi_cleareol = 
#ansi_cleareol = \e[K
ansi_clearescaped = 
#ansi_clearescaped = \033\[K
ansi_home = 
#ansi_home = \e[1G
#am__v_CC_0 = @echo -e "$(ansi_default)$(ansi_cleareol)  CC    " $@;
#am__v_CCLD_0 = @echo -e "$(ansi_default)$(ansi_cleareol)  CCLD  " $@;
#am__v_GEN_0 = @echo -e "$(ansi_default)$(ansi_cleareol)  GEN   " $@;
TSU_V_CP = $(TSU_V_CP_$(V))
TSU_V_CP_ = $(TSU_V_CP_$(AM_DEFAULT_VERBOSITY))
TSU_V_CP_0 = @$(ECHO_ANSI) \
  "$(ansi_cleareol)  $(ansi_default)CP$(ansi_default)    " $@;

TSU_V_TEXL = $(TSU_V_TEXL_$(V))
TSU_V_TEXL_ = $(TSU_V_TEXL_$(AM_DEFAULT_VERBOSITY))
TSU_V_TEXL_0 = $(ECHO_ANSI) \
  "$(ansi_cleareol)  $(ansi_green)TEX$(ansi_default)   " "$@($$I)";


############################################################################

# CONDITIONAL OPTIONS
#BUDDY_LIBS = -lbdd
#MAYBE_CIDATA = chise.eids chise.bvec
#MAYBE_DOCS = idsgrep.pdf
#MAYBE_DOCS = idsgrep.pdf
#expect_start = $(if $(AM_V_at),$(EXPECT) -c \
#    'log_user 0 ; spawn -noecho sh -c ")

expect_end = $(TSU_V_REDIR)
#expect_end = $(if $(AM_V_at), " ; \
#    expect -timeout -1 \
#    -re "\n! " {exit 1} \
#    -re "PROGRESS:(\[^\n\]*)\n" \
#      {puts -nonewline \
#         "$(ansi_clearescaped)$$expect_out(1,string)\r"; \
#       flush stdout;exp_continue} \
#    eof ; wait' )

#MAYBE_COVERAGE = --coverage --no-inline
MAYBE_KVDATA = kanjivg.eids kanjivg.bvec
#MAYBE_TSUKUDATA = tsukurimashou.eids tsukurimashou.bvec
MAYBE_EDICTDATA = edict.eids edict.bvec
MAYBE_CJKVIDATA = $(foreach ver,g t j k v x h a,\
  $(if $(findstring $(ver),$(enable_cjkvi_style)),\
  cjkvi-$(ver).eids cjkvi-$(ver).bvec ))


############################################################################

# TESTING

# must go before "filenames for autotools"
GCOV_TESTS = \
  test/andor test/anynot test/assoc test/basicmatch test/backslash \
  test/bighash test/cooked test/demorgan test/equal test/filtcalc \
  test/genbv test/kvg-grone test/messages test/parsedict test/regex \
  test/spacing test/speed test/ternbv test/truncate test/tsu-grone \
  test/unilist test/unord test/userpred test/utf8

TESTS = $(GCOV_TESTS) test/vgneko
#TESTS = test/rmgcda $(GCOV_TESTS) test/gcov

############################################################################

# FILENAMES FOR AUTOTOOLS

# QVFG and FPEVCGF are DIST and SCRIPTS in ROT13, to keep Automake
# from recognizing them
STANDALONE_QVFG := 
EXTRA_DIST := \
  $(if $(filter $(distdir),$(top_distdir)),$(STANDALONE_QVFG)) \
  gnugetopt.h idsgrep.tex idsgrep.bib widths.txt mkwcw.c

STANDALONE_FPEVCGF := 
dist_noinst_SCRIPTS := \
  $(if $(filter $(distdir),$(top_distdir)),$(STANDALONE_FPEVCGF)) \
  chise2eids cjkvi2eids ed22eids kvg2eids \
  cjkvi-ids.txt \
  $(GCOV_TESTS) test/vgneko test/rmgcda test/gcov

dict_DATA = $(MAYBE_CJKVIDATA) $(MAYBE_CIDATA) $(MAYBE_EDICTDATA) \
  $(MAYBE_KVDATA) $(MAYBE_TSUKUDATA)

dist_pdf_DATA = $(MAYBE_DOCS)
AM_CFLAGS := $(MAYBE_COVERAGE) $(PCRE_CFLAGS) $(AM_CFLAGS)
idsgrep_SOURCES = \
  assoc.c bitvec.c cook.c hash.c idsgrep.c idsgrep.h match.c \
  parse.c regex.c unilist.c userpred.c widthtab.c

mkwcw_SOURCES = mkwcw.c
LDADD =  $(PCRE_LIBS) $(BUDDY_LIBS)
man1_MANS = idsgrep.1

############################################################################

# MAKE CLEAN
MOSTLYCLEANFILES = \
  idsgrep.aux idsgrep.log idsgrep.blg idsgrep.bbl idsgrep.toc \
  *.bvec *.gcda *.gcno *.gcov

CLEANFILES = chise.errs edict.eids kanjivg.eids tsukurimashou.eids
DISTCLEANFILES = \
  $(if $(VPATH),idsgrep.pdf chise.eids,) _stdint.h aminclude.am

MAINTAINERCLEANFILES = idsgrep.pdf chise.eids

############################################################################

# AUTOMAKE'S RULES WILL GO HERE
automake_rules = here
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .html .log .o .obj .test .test$(EXEEXT)
am--refresh:
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then \
	  rm -f stamp-h1; \
	  $(MAKE) $(AM_MAKEFLAGS) stamp-h1; \
	else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
idsgrep.1: $(top_builddir)/config.status $(srcdir)/idsgrep.1.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
config.tex: $(top_builddir)/config.status $(srcdir)/config.tex.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	test -z "$(bindir)" || $(MKDIR_P) "$(DESTDIR)$(bindir)"
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	      echo " $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	      $(INSTALL_PROGRAM_ENV) $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	-test -z "$(bin_PROGRAMS)" || rm -f $(bin_PROGRAMS)

clean-noinstPROGRAMS:
	-test -z "$(noinst_PROGRAMS)" || rm -f $(noinst_PROGRAMS)
idsgrep$(EXEEXT): $(idsgrep_OBJECTS) $(idsgrep_DEPENDENCIES) 
	@rm -f idsgrep$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(idsgrep_OBJECTS) $(idsgrep_LDADD) $(LIBS)
mkwcw$(EXEEXT): $(mkwcw_OBJECTS) $(mkwcw_DEPENDENCIES) 
	@rm -f mkwcw$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(mkwcw_OBJECTS) $(mkwcw_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include $(DEPDIR)/getopt.Po
include $(DEPDIR)/getopt1.Po
include ./$(DEPDIR)/assoc.Po
include ./$(DEPDIR)/bitvec.Po
include ./$(DEPDIR)/cook.Po
include ./$(DEPDIR)/hash.Po
include ./$(DEPDIR)/idsgrep.Po
include ./$(DEPDIR)/match.Po
include ./$(DEPDIR)/mkwcw.Po
include ./$(DEPDIR)/parse.Po
include ./$(DEPDIR)/regex.Po
include ./$(DEPDIR)/unilist.Po
include ./$(DEPDIR)/userpred.Po
include ./$(DEPDIR)/widthtab.Po

.c.o:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ $<
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c $<

.c.obj:
	$(AM_V_CC)$(COMPILE) -MT $@ -MD -MP -MF $(DEPDIR)/$*.Tpo -c -o $@ `$(CYGPATH_W) '$<'`
	$(AM_V_at)$(am__mv) $(DEPDIR)/$*.Tpo $(DEPDIR)/$*.Po
#	$(AM_V_CC) \
#	source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(COMPILE) -c `$(CYGPATH_W) '$<'`
install-man1: $(man1_MANS)
	@$(NORMAL_INSTALL)
	test -z "$(man1dir)" || $(MKDIR_P) "$(DESTDIR)$(man1dir)"
	@list='$(man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	{ for i in $$list; do echo "$$i"; done; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list='$(man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	test -z "$$files" || { \
	  echo " ( cd '$(DESTDIR)$(man1dir)' && rm -f" $$files ")"; \
	  cd "$(DESTDIR)$(man1dir)" && rm -f $$files; }
install-dictDATA: $(dict_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(dictdir)" || $(MKDIR_P) "$(DESTDIR)$(dictdir)"
	@list='$(dict_DATA)'; test -n "$(dictdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(dictdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(dictdir)" || exit $$?; \
	done

uninstall-dictDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dict_DATA)'; test -n "$(dictdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(dictdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(dictdir)" && rm -f $$files
install-dist_pdfDATA: $(dist_pdf_DATA)
	@$(NORMAL_INSTALL)
	test -z "$(pdfdir)" || $(MKDIR_P) "$(DESTDIR)$(pdfdir)"
	@list='$(dist_pdf_DATA)'; test -n "$(pdfdir)" || list=; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pdfdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pdfdir)" || exit $$?; \
	done

uninstall-dist_pdfDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(dist_pdf_DATA)'; test -n "$(pdfdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	test -n "$$files" || exit 0; \
	echo " ( cd '$(DESTDIR)$(pdfdir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(pdfdir)" && rm -f $$files

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

# To be appended to the command running the test.  Handle the stdout
# and stderr redirection, and catch the exit status.
am__check_post =					\
>$@-t 2>&1;						\
estatus=$$?;						\
if test -n '$(DISABLE_HARD_ERRORS)'			\
   && test $$estatus -eq 99; then			\
  estatus=1;						\
fi;							\
TERM=$$__SAVED_TERM; export TERM;			\
$(am__tty_colors);					\
xfailed=PASS;						\
case " $(XFAIL_TESTS) " in				\
  *[\ \	]$$f[\ \	]* | *[\ \	]$$dir$$f[\ \	]*) \
    xfailed=XFAIL;;					\
esac;							\
case $$estatus:$$xfailed in				\
    0:XFAIL) col=$$red; res=XPASS;;			\
    0:*)     col=$$grn; res=PASS ;;			\
    77:*)    col=$$blu; res=SKIP ;;			\
    99:*)    col=$$red; res=FAIL ;;			\
    *:XFAIL) col=$$lgn; res=XFAIL;;			\
    *:*)     col=$$red; res=FAIL ;;			\
esac;							\
echo "$${col}$$res$${std}: $$f";			\
echo "$$res: $$f (exit: $$estatus)" |			\
  $(am__rst_section) >$@;				\
cat $@-t >>$@;						\
rm -f $@-t

$(TEST_SUITE_LOG): $(TEST_LOGS)
	@$(am__sh_e_setup);						\
	list='$(TEST_LOGS)';						\
	results=`for f in $$list; do					\
		   read line < $$f && echo "$$line" || echo FAIL;	\
		 done`;							\
	all=`echo "$$results" | sed '/^$$/d' | wc -l | sed -e 's/^[	 ]*//'`; \
	fail=`echo "$$results" | grep -c '^FAIL'`;			\
	pass=`echo "$$results" | grep -c '^PASS'`;			\
	skip=`echo "$$results" | grep -c '^SKIP'`;			\
	xfail=`echo "$$results" | grep -c '^XFAIL'`;			\
	xpass=`echo "$$results" | grep -c '^XPASS'`;			\
	failures=`expr $$fail + $$xpass`;				\
	all=`expr $$all - $$skip`;					\
	if test "$$all" -eq 1; then tests=test; All=;			\
	else tests=tests; All="All "; fi;				\
	case fail=$$fail:xpass=$$xpass:xfail=$$xfail in			\
	  fail=0:xpass=0:xfail=0)					\
	    msg="$$All$$all $$tests passed.  ";				\
	    exit=true;;							\
	  fail=0:xpass=0:xfail=*)					\
	    msg="$$All$$all $$tests behaved as expected";		\
	    if test "$$xfail" -eq 1; then xfailures=failure;		\
	    else xfailures=failures; fi;				\
	    msg="$$msg ($$xfail expected $$xfailures).  ";		\
	    exit=true;;							\
	  fail=*:xpass=0:xfail=*)					\
	    msg="$$fail of $$all $$tests failed.  ";			\
	    exit=false;;						\
	  fail=*:xpass=*:xfail=*)					\
	    msg="$$failures of $$all $$tests did not behave as expected"; \
	    if test "$$xpass" -eq 1; then xpasses=pass;			\
	    else xpasses=passes; fi;					\
	    msg="$$msg ($$xpass unexpected $$xpasses).  ";		\
	    exit=false;;						\
	  *)								\
	    echo >&2 "incorrect case"; exit 4;;				\
	esac;								\
	if test "$$skip" -ne 0; then					\
	  if test "$$skip" -eq 1; then					\
	    msg="$$msg($$skip test was not run).  ";			\
	  else								\
	    msg="$$msg($$skip tests were not run).  ";			\
	  fi;								\
	fi;								\
	{								\
	  echo "$(PACKAGE_STRING): $(subdir)/$(TEST_SUITE_LOG)" |	\
	    $(am__rst_title);						\
	  echo "$$msg";							\
	  echo;								\
	  echo ".. contents:: :depth: 2";				\
	  echo;								\
	  for f in $$list; do						\
	    read line < $$f;						\
	    case $$line in						\
	      PASS:*|XFAIL:*);;						\
	      *) echo; cat $$f;;					\
	    esac;							\
	  done;								\
	} >$(TEST_SUITE_LOG).tmp;					\
	mv $(TEST_SUITE_LOG).tmp $(TEST_SUITE_LOG);			\
	if test "$$failures" -ne 0; then				\
	  msg="$${msg}See $(subdir)/$(TEST_SUITE_LOG).  ";		\
	  if test -n "$(PACKAGE_BUGREPORT)"; then			\
	    msg="$${msg}Please report to $(PACKAGE_BUGREPORT).  ";	\
	  fi;								\
	fi;								\
	test x"$$VERBOSE" = x || $$exit || cat $(TEST_SUITE_LOG);	\
	$(am__tty_colors);						\
	if $$exit; then							\
	  echo $(ECHO_N) "$$grn$(ECHO_C)";				\
	 else								\
	  echo $(ECHO_N) "$$red$(ECHO_C)";				\
	fi;								\
	echo "$$msg" | $(am__text_box);					\
	echo $(ECHO_N) "$$std$(ECHO_C)";				\
	$$exit

# Run all the tests.
check-TESTS:
	@list='$(RECHECK_LOGS)'; test -z "$$list" || rm -f $$list
	@test -z "$(TEST_SUITE_LOG)" || rm -f $(TEST_SUITE_LOG)
	@list='$(TEST_LOGS)';						\
	list=`for f in $$list; do					\
	  test .log = $$f || echo $$f;					\
	done | tr '\012\015' '  '`;					\
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_LOG) TEST_LOGS="$$list"

.log.html:
	@list='$(RST2HTML) $$RST2HTML rst2html rst2html.py';		\
	for r2h in $$list; do						\
	  if ($$r2h --version) >/dev/null 2>&1; then			\
	    R2H=$$r2h;							\
	  fi;								\
	done;								\
	if test -z "$$R2H"; then					\
	  echo >&2 "cannot find rst2html, cannot create $@";		\
	  exit 2;							\
	fi;								\
	$$R2H $< >$@.tmp
	@mv $@.tmp $@

# Be sure to run check first, and then to convert the result.
# Beware of concurrent executions.  Run "check" not "check-TESTS", as
# check-SCRIPTS and other dependencies are rebuilt by the former only.
# And expect check to fail.
check-html:
	@if $(MAKE) $(AM_MAKEFLAGS) check; then			\
	  rv=0; else rv=$$?;					\
	fi;							\
	$(MAKE) $(AM_MAKEFLAGS) $(TEST_SUITE_HTML) || exit 4;	\
	exit $$rv
recheck recheck-html:
	@target=`echo $@ | sed 's,^re,,'`;				\
	list='$(TEST_LOGS)';						\
	list=`for f in $$list; do					\
	        test -f $$f || continue;				\
	        if read line < $$f; then				\
	          case $$line in FAIL*|XPASS*) echo $$f;; esac;		\
	        else echo $$f; fi;					\
	      done | tr '\012\015' '  '`;				\
	$(MAKE) $(AM_MAKEFLAGS) $$target AM_MAKEFLAGS='$(AM_MAKEFLAGS) TEST_LOGS="'"$$list"'"'
test/andor.log: test/andor
	@p='test/andor'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/anynot.log: test/anynot
	@p='test/anynot'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/assoc.log: test/assoc
	@p='test/assoc'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/basicmatch.log: test/basicmatch
	@p='test/basicmatch'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/backslash.log: test/backslash
	@p='test/backslash'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/bighash.log: test/bighash
	@p='test/bighash'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/cooked.log: test/cooked
	@p='test/cooked'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/demorgan.log: test/demorgan
	@p='test/demorgan'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/equal.log: test/equal
	@p='test/equal'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/filtcalc.log: test/filtcalc
	@p='test/filtcalc'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/genbv.log: test/genbv
	@p='test/genbv'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/kvg-grone.log: test/kvg-grone
	@p='test/kvg-grone'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/messages.log: test/messages
	@p='test/messages'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/parsedict.log: test/parsedict
	@p='test/parsedict'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/regex.log: test/regex
	@p='test/regex'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/spacing.log: test/spacing
	@p='test/spacing'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/speed.log: test/speed
	@p='test/speed'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/ternbv.log: test/ternbv
	@p='test/ternbv'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/truncate.log: test/truncate
	@p='test/truncate'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/tsu-grone.log: test/tsu-grone
	@p='test/tsu-grone'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/unilist.log: test/unilist
	@p='test/unilist'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/unord.log: test/unord
	@p='test/unord'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/userpred.log: test/userpred
	@p='test/userpred'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/utf8.log: test/utf8
	@p='test/utf8'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/vgneko.log: test/vgneko
	@p='test/vgneko'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/rmgcda.log: test/rmgcda
	@p='test/rmgcda'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
test/gcov.log: test/gcov
	@p='test/gcov'; $(am__check_pre) $(LOG_COMPILE) "$$tst" $(am__check_post)
.test.log:
	@p='$<'; $(am__check_pre) $(TEST_LOG_COMPILE) "$$tst" $(am__check_post)
#.test$(EXEEXT).log:
#	@p='$<'; $(am__check_pre) $(TEST_LOG_COMPILE) "$$tst" $(am__check_post)

distdir: $(DISTFILES)
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | bzip2 -9 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod u+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@$(am__cd) '$(distuninstallcheck_dir)' \
	&& test `$(distuninstallcheck_listfiles) | wc -l` -le 1 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(PROGRAMS) $(SCRIPTS) $(MANS) $(DATA) config.h
installdirs:
	for dir in "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(dictdir)" "$(DESTDIR)$(pdfdir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	$(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	  install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	  `test -z '$(STRIP)' || \
	    echo "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'"` install
mostlyclean-generic:
	-test -z "$(MOSTLYCLEANFILES)" || rm -f $(MOSTLYCLEANFILES)
	-test -z "$(TEST_LOGS)" || rm -f $(TEST_LOGS)
	-test -z "$(TEST_LOGS_TMP)" || rm -f $(TEST_LOGS_TMP)
	-test -z "$(TEST_SUITE_HTML)" || rm -f $(TEST_SUITE_HTML)
	-test -z "$(TEST_SUITE_LOG)" || rm -f $(TEST_SUITE_LOG)

clean-generic:
	-test -z "$(CLEANFILES)" || rm -f $(CLEANFILES)

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-test -z "$(DISTCLEANFILES)" || rm -f $(DISTCLEANFILES)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
	-test -z "$(MAINTAINERCLEANFILES)" || rm -f $(MAINTAINERCLEANFILES)
clean: clean-am

clean-am: clean-binPROGRAMS clean-generic clean-noinstPROGRAMS \
	mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(DEPDIR) ./$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-dictDATA install-dist_pdfDATA install-man

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS

install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf $(DEPDIR) ./$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-dictDATA \
	uninstall-dist_pdfDATA uninstall-man

uninstall-man: uninstall-man1

.MAKE: all check-am check-html install-am install-strip recheck \
	recheck-html

.PHONY: CTAGS GTAGS all all-am am--refresh check check-TESTS check-am \
	check-html clean clean-binPROGRAMS clean-generic \
	clean-noinstPROGRAMS ctags dist dist-all dist-bzip2 dist-gzip \
	dist-lzma dist-shar dist-tarZ dist-xz dist-zip distcheck \
	distclean distclean-compile distclean-generic distclean-hdr \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am \
	install-dictDATA install-dist_pdfDATA install-dvi \
	install-dvi-am install-exec install-exec-am install-html \
	install-html-am install-info install-info-am install-man \
	install-man1 install-pdf install-pdf-am install-ps \
	install-ps-am install-strip installcheck installcheck-am \
	installdirs maintainer-clean maintainer-clean-generic \
	mostlyclean mostlyclean-compile mostlyclean-generic pdf pdf-am \
	ps ps-am recheck recheck-html tags uninstall uninstall-am \
	uninstall-binPROGRAMS uninstall-dictDATA \
	uninstall-dist_pdfDATA uninstall-man uninstall-man1


include $(top_builddir)/aminclude.am
#$(error Cannot use --enable-widthtab without BuDDy)

define GCDEP_RECIPE
$1.log: test/rmgcda.log

endef

#  $(foreach test,$(GCOV_TESTS),$(eval $(call GCDEP_RECIPE,$(test))))

#  test/gcov.log: $(foreach test,$(GCOV_TESTS),$(test).log)

############################################################################

# PDF DOCUMENTATION

idsgrep.pdf: idsgrep.tex config.tex idsgrep.bib \
  no/otf/TsukurimashouMincho.otf
	$(AM_V_at)I=1;$(TSU_V_TEXL) \
	  $(expect_start)$(XELATEX) $(mvp)/idsgrep.tex $(expect_end) ; \
	export BIBINPUTS=$(mvp) ; bibtex idsgrep.aux $(TSU_V_REDIR) ; \
	I=2;$(TSU_V_TEXL) \
	  $(expect_start)$(XELATEX) $(mvp)/idsgrep.tex $(expect_end) ; \
	I=3;$(TSU_V_TEXL) \
	  $(expect_start)$(XELATEX) $(mvp)/idsgrep.tex $(expect_end)

############################################################################

# DICTIONARIES

chise.eids: $(wildcard no/IDS-*.txt) chise2eids
	$(PERL) -CDS $(mvp)/chise2eids \
	  no no/IDS-*.txt \
	  > chise.eids 2> chise.errs
	echo `wc -l < chise.errs` errors detected in CHISE IDS

cjkvi-%.eids: cjkvi-ids.txt cjkvi2eids
	$(PERL) -CDS $(mvp)/cjkvi2eids $* \
	  $(mvp)/cjkvi-ids.txt > cjkvi-$*.eids

edict.eids: ./edict2.gz cjkvi-j.eids ed22eids
	$(GZIP) -cd ./edict2.gz \
	  | $(ICONV) -feuc-jp -tutf-8 \
	  | $(PERL) -CDS $(mvp)/ed22eids cjkvi-j.eids > edict.eids

kanjivg.eids: ./kanjivg-20140816.xml.gz kvg2eids
	if $(PERL) \
	  -e 'read STDIN,$$_,2;exit 1 if unpack("n",$$_)!=8075' \
	  < ./kanjivg-20140816.xml.gz ; \
	then $(GZIP) -cd ./kanjivg-20140816.xml.gz \
	  | $(PERL) -CS $(mvp)/kvg2eids > kanjivg.eids ; \
	else $(PERL) -CS $(mvp)/kvg2eids < ./kanjivg-20140816.xml.gz > kanjivg.eids ; fi

no/otf/TsukurimashouMincho.otf:
	cd no ; \
	  $(MAKE) $(AM_MAKEFLAGS) otf/TsukurimashouMincho.otf

no/txt/tsukurimashou.eids: Makefile
	cd no ; $(MAKE) $(AM_MAKEFLAGS) eids

tsukurimashou.eids: no/txt/tsukurimashou.eids
	$(LN_S) -f no/txt/tsukurimashou.eids \
	  tsukurimashou.eids

%.bvec: idsgrep %.eids
	$(AM_V_GEN)
	$(AM_V_at)./idsgrep -G $*.eids > $*.bvec

############################################################################

# BUILD THE WIDTH TABLE

#widthtab.c: mkwcw widths.txt EastAsianWidth.txt UnicodeData.txt
#	cat widths.txt EastAsianWidth.txt | ./mkwcw N UnicodeData.txt \
#	  > widthtab.c

############################################################################

# PARASITE BUILD

#m4/ax_add_am_macro.m4: ../m4/ax_add_am_macro.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_am_jobserver.m4: ../m4/ax_am_jobserver.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_am_macros.m4: ../m4/ax_am_macros.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_append_to_file.m4: ../m4/ax_append_to_file.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_check_gnu_make.m4: ../m4/ax_check_gnu_make.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_create_stdint_h.m4: ../m4/ax_create_stdint_h.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_count_cpus.m4: ../m4/ax_count_cpus.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_file_escapes.m4: ../m4/ax_file_escapes.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_perl_module_version.m4: ../m4/ax_perl_module_version.m4
#	$(TSU_V_CP) cp $< $@

#m4/ax_print_to_file.m4: ../m4/ax_print_to_file.m4
#	$(TSU_V_CP) cp $< $@

############################################################################

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
